//tealium universal tag - utag.315 ut4.0.201911211950, Copyright 2019 Tealium.com Inc. All Rights Reserved.
var MoxieData=MoxieData||{};var addedListeners=addedListeners||{};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={"tenant":"tenant","cp.grpId":"custom.grpId","js_page.USAA.ent.digitalData.page.pageID":"custom.pageid"};u.extend=[function(a,b){try{if(1){var tT={};var sR={"ent-eligibility":95,"pc-claims-member-appraisal-assignment":50,"WRMBRLSRPTAUTO":50,"WRMBLLSRPTAUTO":50};if(sR[b['js_page.USAA.ent.digitalData.page.attributes.appId']]===0){sR[b['js_page.USAA.ent.digitalData.page.attributes.appId']]=1;}
sample_rate=sR[b['js_page.USAA.ent.digitalData.page.attributes.appId']]||100;var cV='useMoxie'+b['js_page.USAA.ent.digitalData.page.attributes.appId'];var cP='cp.utag_main_'+cV;if(b[cP]&&b[cP].match(/false/)){return false;}
else{if(!b[cP]){var useMoxie=(Math.random()<(sample_rate/100))?"true":"false";if(useMoxie.match(/false/)){tT['useMoxie'+b['js_page.USAA.ent.digitalData.page.attributes.appId']]="false"+";exp-7d";utag.loader.SC('utag_main',tT);return false;}}}
tT['useMoxie'+b['js_page.USAA.ent.digitalData.page.attributes.appId']]="true"+";exp-7d";utag.loader.SC('utag_main',tT);}}catch(e){utag.DB(e)}},function(a,b,c,d,e,f,g){if(1){d=b['js_page.USAA.ent.digitalData.page.attributes.appId'];if(typeof d=='undefined')return;c=[{'ent-eligibility':'usaaeligibility'},{'pc-claims-member-appraisal-assignment':'usaaclaims'},{'WRMBRLSRPTAUTO':'usaaclaims'},{'WRMBLLSRPTAUTO':'usaaclaims'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['tenant']=c[e][f];m=true};};if(m)break};if(!m)b['tenant']='';}},function(a,b){try{if(1){var url=b['dom.domain'];if(!url.match(/^(www|mobile|mobileapps)\.usaa\.com$/))
{b['tenant']=b["tenant"]+"test";}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){var eventsToListenFor=['GoMoxie:bellClicked','GoMoxie:widgetOpened','GoMoxie:widgetMinimised','GoMoxie:widgetClosed','GoMoxie:proactiveOffer','GoMoxie:widget:kb:articleViewed','GoMoxie:widget:kb:portalSearched'];function addWindowListenerIfNone(eventType,fun){if(addedListeners[eventType])return;addedListeners[eventType]=fun;window.addEventListener(eventType,fun);}
for(i=0;i<eventsToListenFor.length;i++){addWindowListenerIfNone(eventsToListenFor[i],handleMoxieEvent);}
if(USAA.ent.digitalData)USAA.ent.digitalData.event.push({'eventName':'520','attributes':{}});function handleMoxieEvent(e){if(e.detail.detail){e={detail:e.detail.detail,type:e.type};}
var eventData=evaluateEvent(e);if(eventData!=null){var eVars="";for(var key in eventData){if(eventData[key]!="undefined"&&eventData[key]!=""){if(key.match(/^custom/i)){custom=key;USAA.ent.digitalData.component.attributes[custom]=eventData[key];}
else if(key.match(/^event/i)){USAA.ent.digitalData.event.push({'eventName':eventData[key],'attributes':{}});}
else if(key.match(/linkName/i)){USAA.ent.digitalData.component.attributes.custom70=eventData[key];}}}
utag.link(USAA.ent.digitalData,null,[233]);USAA.ent.digitalData.component.attributes.custom70='';USAA.ent.digitalData.component.attributes.custom71='';USAA.ent.digitalData.component.attributes.custom72='';USAA.ent.digitalData.component.attributes.custom73='';if(USAA.ent.digitalData.event&&USAA.ent.digitalData.event.eventName!='520')USAA.ent.digitalData.event.pop();}}
function evaluateEvent(e){var config=eventsConfiguration[e.type];var eventData=[];var getType={};if(config&&typeof config==='function'){config=config(e);}
for(var key in config){eventData[key]=evaluateVars(config[key],e);}
return eventData;}
function evaluateVars(varsString,sourceObject){var stringEvaluated="";var varsStringBroken=varsString.split('<');for(i=0;i<varsStringBroken.length;i++){var dynamicParam=varsStringBroken[i]
if(dynamicParam.indexOf(">")>-1){var firstIndex=dynamicParam.indexOf(">");var eventValueFromObject=geteventValueFromObject(dynamicParam.slice(0,firstIndex),sourceObject)
stringEvaluated=stringEvaluated+eventValueFromObject+dynamicParam.slice(firstIndex+1);}else{stringEvaluated=stringEvaluated+dynamicParam;}}
return stringEvaluated;}
function geteventValueFromObject(name,obj){if(name.indexOf(".")>-1){var firstIndex=name.indexOf(".");return geteventValueFromObject(name.slice(firstIndex+1),obj[name.slice(0,firstIndex)]);}else{return obj[name];}}
var eventsConfiguration=[];eventsConfiguration['GoMoxie:bellClicked']={"custom71":"Moxie:user-initiated",events:"501",linkName:"Moxie:Bell Clicked"};eventsConfiguration['GoMoxie:widgetOpened']={"custom71":"Moxie:user-initiated","custom72":"Moxie:<detail.widgetName>",events:"502",linkName:"Moxie:Widget Opened"};eventsConfiguration['GoMoxie:widgetMinimised']={"custom71":"Moxie:user-initiated","custom72":"Moxie:<detail.widgetName>",events:"503",linkName:"Moxie:Widget Minimised"};eventsConfiguration['GoMoxie:widgetClosed']={"custom71":"Moxie:user-initiated","custom72":"Moxie:<detail.widgetName>",events:"504",linkName:"Moxie:Widget Closed"};eventsConfiguration['GoMoxie:proactiveOffer']=function(e){if(e.detail.status=="accepted"){return{"custom71":"Moxie:auto-initiated","custom72":"Moxie:<detail.rule.id>:<detail.rule.name>",events:"505",linkName:"Moxie:Proactive Offer Accepted"};}
if(e.detail.status=="declined"){return{"custom71":"Moxie:auto-initiated","custom72":"Moxie:<detail.rule.id>:<detail.rule.name>",events:"506",linkName:"Moxie:Proactive Offer Declined"};;}
if(e.detail.status=="displayed"){return{"custom71":"Moxie:auto-initiated","custom72":"Moxie:<detail.rule.id>:<detail.rule.name>",events:"507",linkName:"Moxie:Proactive Offer Shown"};;}
return null;}
eventsConfiguration['GoMoxie:widget:kb:articleViewed']={"custom71":"Moxie:user-initiated","custom73":"Moxie:<detail.articleId>:<detail.articleTitle>",events:"517",linkName:"Moxie:KB Article Viewed"};eventsConfiguration['GoMoxie:widget:kb:portalSearched']={"custom71":"Moxie:user-initiated","custom73":"Moxie:<detail.searchText>",events:"518",linkName:"Moxie:KB Portal Searched"};}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"base_url":"https://asset.gomoxie.solutions/concierge/##utag_tenant##/client/concierge-client.js","tenant":"","custom":{},};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("custom.")===0){u.data.custom[e[f].substr(7)]=b[d];}else{u.data[e[f]]=b[d];}}}else{h=d.split(":");if(h.length==2&&b[h[0]]==h[1]){g=""+u.event_lookup[u.map[d]];if(g!=""){b._cevent=g;}}}}
u.data.base_url=u.data.base_url.replace("##utag_tenant##",u.data.tenant);u.s=document.getElementsByTagName("script")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.data.base_url;u.scr.setAttribute("concierge","1");if(typeof MoxieData.loaded=='undefined'){MoxieData={"loaded":true};u.s.parentNode.insertBefore(u.scr,u.s);}
}};utag.o[loader].loader.LOAD(id);}("315","usaa.nw"));}catch(error){utag.DB(error);}
